"""Shared pytest fixtures.

We deliberately make every test load settings from a clean environment so
that a stray ``.env`` in the working directory cannot influence results.
"""

from __future__ import annotations

import os
from collections.abc import Iterator

import pytest


_ENV_KEYS_TO_RESET = {
    "MODE",
    "LIVE_ADAPTER_CONFIRMED",
    "INSTRUMENT",
    "MARKET_TYPE",
    "TIMEZONE",
    "DATABASE_URL",
    "TRADING_WINDOW_START",
    "TRADING_WINDOW_END",
    "FORCE_FLAT_TIME",
    "MAX_DAILY_LOSS",
    "MAX_DAILY_PROFIT",
    "MAX_TRADES_PER_DAY",
    "MAX_POSITION_SIZE",
    "RISK_PER_TRADE",
    "CONFIDENCE_THRESHOLD",
    "SLIPPAGE_TICKS",
    "COMMISSION_PER_CONTRACT",
    "CRYPTO_SLIPPAGE_BPS",
    "CRYPTO_FEE_BPS",
    "CONSISTENCY_LIMIT_PERCENT",
    "ENABLE_LLM_AGENTS",
    "OPENAI_API_KEY",
    "LLM_MODEL",
    "LLM_TIMEOUT_SECONDS",
    "AGENTS_RUN_AT_EOD",
    "NEWS_CHECK_LOCAL_TIME",
    "LOG_LEVEL",
    "LOG_JSON",
    "ENABLED_STRATEGIES",
    "ENABLED_SYMBOLS",
    "PRIMARY_SYMBOL",
    "MAX_ACTIVE_SYMBOLS",
    "MAX_TRADES_PER_SYMBOL_PER_DAY",
    "MAX_TOTAL_TRADES_PER_DAY",
    "FEEDBACK_MIN_ROWS",
    "FEEDBACK_USE_MISTAKE_TAGS_AS_LABEL",
    "TRADINGVIEW_WEBHOOK_SECRET",
    "WEBHOOK_DEFAULT_STOP_TICKS",
    "WEBHOOK_DEFAULT_TARGET_TICKS",
    "PERPLEXITY_API_KEY",
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "OPENAI_MODEL",
    "PERPLEXITY_MODEL",
    "ANTHROPIC_MODEL",
    "GEMINI_MODEL",
    "NEWS_AGENT_PROVIDER",
    "MACRO_NEWS_AGENT_PROVIDER",
    "STRATEGY_RESEARCH_AGENT_PROVIDER",
    "TRADE_ANALYSIS_AGENT_PROVIDER",
    "MODEL_REVIEW_AGENT_PROVIDER",
    "REPORT_AGENT_PROVIDER",
    "RISK_EXPLAINER_AGENT_PROVIDER",
    "TRADE_JOURNAL_AGENT_PROVIDER",
    "BACKTEST_CRITIC_AGENT_PROVIDER",
    "MODEL_DRIFT_AGENT_PROVIDER",
    "DATA_QUALITY_AGENT_PROVIDER",
    # Per-agent model overrides + default-model knobs.
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_REVIEW_MODEL",
    "PERPLEXITY_DEFAULT_MODEL",
    "NEWS_AGENT_MODEL",
    "MACRO_NEWS_AGENT_MODEL",
    "STRATEGY_RESEARCH_AGENT_MODEL",
    "TRADE_ANALYSIS_AGENT_MODEL",
    "MODEL_REVIEW_AGENT_MODEL",
    "REPORT_AGENT_MODEL",
    "RISK_EXPLAINER_AGENT_MODEL",
    "TRADE_JOURNAL_AGENT_MODEL",
    "BACKTEST_CRITIC_AGENT_MODEL",
    "MODEL_DRIFT_AGENT_MODEL",
    "DATA_QUALITY_AGENT_MODEL",
    "WORKFLOW_EXECUTION_MODE",
    "WORKFLOW_TIMEZONE",
    "WORKFLOW_WEEKDAYS_ONLY",
    "WORKFLOW_LONG_ONLY",
    "WORKFLOW_NO_ENTRY_MINUTES_BEFORE_CLOSE",
    "WORKFLOW_GIT_COMMIT",
    "WORKFLOW_GIT_PUSH",
    "PERPLEXITY_ENABLED",
    "AUTONOMOUS_TRADING_ENABLED",
    "AUTONOMOUS_PAPER_ONLY",
    "WORKFLOW_MEMORY_DIR",
    "WORKFLOW_MODEL_NAME",
    "WORKFLOW_MODEL_VERSION",
    "WORKFLOW_REQUIRE_SIGNAL",
    "USE_RISK_BASED_SIZING",
    "MAX_SHARES_PER_TRADE",
    "MAX_NOTIONAL_PER_TRADE",
    "STRATEGY_SKIP_OPEN_MINUTES",
    "STRATEGY_SKIP_CLOSE_MINUTES",
    "MIN_STOP_DISTANCE_PCT",
    "MIN_STOP_DISTANCE_CENTS",
    "WORKFLOW_SCAN_INTERVAL_MINUTES",
    "WORKFLOW_REFRESH_DATA_EACH_SCAN",
    "WORKFLOW_LONG_ONLY",
    "WORKFLOW_DYNAMIC_UNIVERSE",
    "WORKFLOW_MAX_UNIVERSE",
    "WORKFLOW_AGENT_WATCHLIST",
    "BROKER_PROVIDER",
    "DEFAULT_ORDER_TYPE",
    "BROKER_REQUEST_TIMEOUT_SECONDS",
    "TRADOVATE_USERNAME",
    "TRADOVATE_PASSWORD",
    "TRADOVATE_APP_ID",
    "TRADOVATE_APP_VERSION",
    "TRADOVATE_CLIENT_ID",
    "TRADOVATE_CLIENT_SECRET",
    "TRADOVATE_DEMO",
    "TRADOVATE_BASE_URL",
    "TRADOVATE_WS_URL",
    "ALPACA_API_KEY",
    "ALPACA_SECRET_KEY",
    "ALPACA_PAPER",
    "ALPACA_BASE_URL",
    "ENABLE_PARALLEL_PAPER",
    "PARALLEL_BROKERS",
    "ALPACA_ENABLED_SYMBOLS",
    "FUTURES_SIM_ENABLED_SYMBOLS",
    "ALPACA_EVALUATION_ID",
    "FUTURES_SIM_EVALUATION_ID",
    "ALPACA_STATE_PATH",
    "FUTURES_SIM_STATE_PATH",
    "OPTIONS_ENABLED",
    "OPTIONS_STRATEGY",
    "OPTIONS_DEFAULT_DTE",
    "OPTIONS_MIN_DTE",
    "OPTIONS_MAX_DTE",
    "OPTIONS_TARGET_DELTA",
    "OPTIONS_SPREAD_WIDTH_STRIKES",
    "OPTIONS_MAX_PREMIUM_PER_TRADE",
    "OPTIONS_MAX_OPEN_POSITIONS",
    "OPTIONS_AUTO_CLOSE_DTE",
    "OPTIONS_AUTO_ROLL",
    "OPTIONS_ROLL_DTE_TRIGGER",
    "OPTIONS_PROFIT_TARGET_PCT",
    "OPTIONS_STOP_LOSS_PCT",
    "OPTIONS_QTY_PER_TRADE",
    "OPTIONS_STATE_PATH",
    "OPTIONS_ENABLED_UNDERLYINGS",
}


@pytest.fixture(autouse=True)
def _isolated_env(monkeypatch: pytest.MonkeyPatch, tmp_path) -> Iterator[None]:
    # Wipe any env vars that could pollute Settings construction.
    for key in _ENV_KEYS_TO_RESET:
        monkeypatch.delenv(key, raising=False)

    # Use a temp DB and prevent reading a real .env.
    db_path = tmp_path / "test.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_path}")
    # Pydantic-settings still tries to read .env from cwd; redirect to /dev/null.
    monkeypatch.chdir(tmp_path)

    # Reset cached singletons in app modules.
    from config import settings as cfg
    from storage import db as db_mod

    cfg._settings = None
    db_mod.reset_engine_for_tests()

    yield

    cfg._settings = None
    db_mod.reset_engine_for_tests()
